{{- if and .Values.serviceMonitor.enabled ( not .Values.podMonitor.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Namespace }}-service-monitor
  labels:
    prometheus: {{ required "required '.Values.prometheus' is not specified" .Values.prometheus }}

spec:
  selector:
    matchLabels:
    {{- range .Values.labelSelector }}
      {{ .key }}: {{ .value | quote }}
    {{- end }}
  
  namespaceSelector:
    matchNames:
    {{  default (list .Release.Namespace ) .Values.namespaces | toYaml | indent 6 }}
  
  endpoints:
    - interval: {{ default "60s" .Values.scrapeInterval }}
      scrapeTimeout: {{ default "55s" .Values.scrapeTimeout }}
      port: {{ default "metrics" .Values.metricsPort }}
      path: {{ default "/metrics" .Values.metricsPath }}
      honorLabels: {{ default true .Values.honorLabels }}
      relabelings: 
        - action: labelmap
          regex: '__meta_kubernetes_pod_label_(.+)'
        - sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: kubernetes_namespace
        - sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: kubernetes_pod_name
{{ include "prometheus.defaultRelabelConfig" .  | indent 8 }}
{{ .Values.customRelabelings | toYaml | indent 8 }}
{{- if .Values.customMetricRelabelings }}
      metricRelabelings:
{{ .Values.customMetricRelabelings | toYaml | indent 8 }}
{{- end }}
{{- end }}
