global:
  region: test-region
  clusterType: test

podMonitor:
  enabled: true
serviceMonitor:
  enabled: false

prometheus: dummy-prometheus

namespaces:
  - "my-namespace"

matchLabels:
  - key: "app.kubernetes.io/name"
    value: "my-app"

customRelabelings:
  - action: labelmap
    sourceLabels:
      - __test__

customMetricRelabelings:
  - action: drop
    regex: ".*"
    sourceLabels: [__name__]
